 Fri 23 Jan 2015 08:13:41 PM PST#my linux is Chinese verion, so some characters might not be able to display.
]0;jysun@jysun-vir-machine: ~/cs100/rshell/testsjysun@jysun-vir-machine:~/cs100/rshell/tests$ make[K[K[K[Kcd ..
]0;jysun@jysun-vir-machine: ~/cs100/rshelljysun@jysun-vir-machine:~/cs100/rshell$ make[K[K[K[Kls
LICENSE  Makefile  README.md  [0m[01;34msrc[0m  [01;34mtests[0m
]0;jysun@jysun-vir-machine: ~/cs100/rshelljysun@jysun-vir-machine:~/cs100/rshell$ me[Kake#makefile
mkdir bin
g++ -ansi -pedantic -Wall -Werror -c ./src/shll6comment.cpp ./src/rshell.h -o ./bin/shll6comment.o
g++ -ansi -pedantic -Wall -Werror -c ./src/setup.cpp -o ./bin/setup.o
g++ -ansi -pedantic -Wall -Werror -c ./src/and_or.cpp ./src/rshell.h -o ./bin/and_or.o
g++ -ansi -pedantic -Wall -Werror -c ./src/smcln.cpp -o ./bin/smcln.o
g++ ./src/shll6comment.cpp ./src/setup.cpp ./src/and_or.cpp ./src/smcln.cpp -o ./bin/rshell
]0;jysun@jysun-vir-machine: ~/cs100/rshelljysun@jysun-vir-machine:~/cs100/rshell$ le[Ks
[0m[01;34mbin[0m  LICENSE  Makefile  README.md  [01;34msrc[0m  [01;34mtests[0m
]0;jysun@jysun-vir-machine: ~/cs100/rshelljysun@jysun-vir-machine:~/cs100/rshell$ ./bin/rshell#begin test
COMMAND->ps#single command is ok
  PID TTY          TIME CMD
 9088 pts/0    00:00:00 bash
 9132 pts/0    00:00:00 rshell
 9133 pts/0    00:00:00 ps
COMMAND->ps;#semicolon is ok
  PID TTY          TIME CMD
 9088 pts/0    00:00:00 bash
 9132 pts/0    00:00:00 rshell
 9135 pts/0    00:00:00 ps
COMMAND->   ps  ;#front and rear blanks are ok
  PID TTY          TIME CMD
 9088 pts/0    00:00:00 bash
 9132 pts/0    00:00:00 rshell
 9136 pts/0    00:00:00 ps
COMMAND->   ps     #same without ; at end 
  PID TTY          TIME CMD
 9088 pts/0    00:00:00 bash
 9132 pts/0    00:00:00 rshell
 9137 pts/0    00:00:00 ps
COMMAND->	ps		;#test with backward tab
  PID TTY          TIME CMD
 9088 pts/0    00:00:00 bash
 9132 pts/0    00:00:00 rshell
 9139 pts/0    00:00:00 ps
COMMAND->		ps	#test with forward tab
  PID TTY          TIME CMD
 9088 pts/0    00:00:00 bash
 9132 pts/0    00:00:00 rshell
 9140 pts/0    00:00:00 ps
COMMAND-> ls   -a#single parameter
.  ..  bin  .git  LICENSE  Makefile  README.md	src  tests
COMMAND->  ls   -a  -l# multi parameters
总用量 36
drwxrwxr-x 6 jysun jysun 4096 Jan 23 20:14 .
drwxrwxr-x 8 jysun jysun 4096 Jan 23 18:47 ..
drwxrwxr-x 2 jysun jysun 4096 Jan 23 20:14 bin
drwxrwxr-x 8 jysun jysun 4096 Jan 23 19:37 .git
-rw-rw-r-- 1 jysun jysun  177 Jan 23 12:03 LICENSE
-rw-rw-r-- 1 jysun jysun  683 Jan 23 18:32 Makefile
-rw-rw-r-- 1 jysun jysun   70 Jan 23 15:05 README.md
drwxrwxr-x 2 jysun jysun 4096 Jan 23 20:05 src
drwxrwxr-x 2 jysun jysun 4096 Jan 23 20:13 tests
COMMAND->  ls -al#multi parameter other version
总用量 36
drwxrwxr-x 6 jysun jysun 4096 Jan 23 20:14 .
drwxrwxr-x 8 jysun jysun 4096 Jan 23 18:47 ..
drwxrwxr-x 2 jysun jysun 4096 Jan 23 20:14 bin
drwxrwxr-x 8 jysun jysun 4096 Jan 23 19:37 .git
-rw-rw-r-- 1 jysun jysun  177 Jan 23 12:03 LICENSE
-rw-rw-r-- 1 jysun jysun  683 Jan 23 18:32 Makefile
-rw-rw-r-- 1 jysun jysun   70 Jan 23 15:05 README.md
drwxrwxr-x 2 jysun jysun 4096 Jan 23 20:05 src
drwxrwxr-x 2 jysun jysun 4096 Jan 23 20:13 tests
COMMAND->ls    -a    -a    -a    -a#repeat same parameters
.  ..  bin  .git  LICENSE  Makefile  README.md	src  tests
COMMAND->ps&&ps# &&
  PID TTY          TIME CMD
 9088 pts/0    00:00:00 bash
 9132 pts/0    00:00:00 rshell
 9149 pts/0    00:00:00 ps
  PID TTY          TIME CMD
 9088 pts/0    00:00:00 bash
 9132 pts/0    00:00:00 rshell
 9150 pts/0    00:00:00 ps
COMMAND->ps&ps# &
  PID TTY          TIME CMD
 9088 pts/0    00:00:00 bash
 9132 pts/0    00:00:00 rshell
 9152 pts/0    00:00:00 ps
  PID TTY          TIME CMD
 9088 pts/0    00:00:00 bash
 9132 pts/0    00:00:00 rshell
 9153 pts/0    00:00:00 ps
COMMAND->ps||ps# ||
  PID TTY          TIME CMD
 9088 pts/0    00:00:00 bash
 9132 pts/0    00:00:00 rshell
 9154 pts/0    00:00:00 ps
COMMAND->ps|ps# |
  PID TTY          TIME CMD
 9088 pts/0    00:00:00 bash
 9132 pts/0    00:00:00 rshell
 9155 pts/0    00:00:00 ps
COMMAND->sp||ls&&pwd# combination of && and ||
execvp fail: No such file or directory
bin  LICENSE  Makefile	README.md  src	tests
/home/jysun/cs100/rshell
COMMAND->	sp;ps  &&pwd;   ls ||pwd# combination of && || ;
execvp fail: No such file or directory
  PID TTY          TIME CMD
 9088 pts/0    00:00:00 bash
 9132 pts/0    00:00:00 rshell
 9163 pts/0    00:00:00 ps
/home/jysun/cs100/rshell
bin  LICENSE  Makefile	README.md  src	tests
COMMAND->ps&&&ps# &&&
  PID TTY          TIME CMD
 9088 pts/0    00:00:00 bash
 9132 pts/0    00:00:00 rshell
 9166 pts/0    00:00:00 ps
COMMAND->sl|||ls#  |||
execvp fail: No such file or directory
bin  LICENSE  Makefile	README.md  src	tests
COMMAND->;;#several NULL
COMMAND->	; ;	;#several blanks
COMMAND->ls  &exit# exit in combination , not work
bin  LICENSE  Makefile	README.md  src	tests
execvp fail: No such file or directory
COMMAND->exit# exit function
]0;jysun@jysun-vir-machine: ~/cs100/rshelljysun@jysun-vir-machine:~/cs100/rshell$ exit
exit

 Fri 23 Jan 2015 08:19:10 PM PST
